//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadBread.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadBread.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Configs&quot;
        ///{
        ///	&quot;Games&quot;
        ///	{
        ///		&quot;%s1&quot;
        ///		{
        ///			&quot;GameDir&quot;		&quot;..\%s2&quot;
        ///			&quot;Hammer&quot;
        ///			{
        ///				&quot;GameData0&quot;		&quot;..\%s2\fgd\game.fgd&quot;
        ///				&quot;TextureFormat&quot;		&quot;5&quot;
        ///				&quot;MapFormat&quot;		&quot;4&quot;
        ///				&quot;DefaultTextureScale&quot;		&quot;0.250000&quot;
        ///				&quot;DefaultLightmapScale&quot;		&quot;16&quot;
        ///				&quot;GameExe&quot;		&quot;..\hl2.exe&quot;
        ///				&quot;DefaultSolidEntity&quot;		&quot;func_detail&quot;
        ///				&quot;DefaultPointEntity&quot;		&quot;prop_static&quot;
        ///				&quot;BSP&quot;		&quot;.\vbsp.exe&quot;
        ///				&quot;Vis&quot;		&quot;.\vvis.exe&quot;
        ///				&quot;Light&quot;		&quot;.\vrad.exe&quot;
        ///				&quot;GameExeDir&quot;		&quot;..&quot;
        ///				&quot;MapDir&quot;		&quot;..\%s2\mapsrc&quot;
        ///				&quot;BSPDir&quot;		&quot;..\%s2\m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hammerTemplate {
            get {
                return ResourceManager.GetString("hammerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reperio_studios {
            get {
                object obj = ResourceManager.GetObject("reperio_studios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
